### ISSUE TITLE
Blank slate

### ISSUE THREAD

**Issue by fulldecent** [ccabanero/ios-unit-testing-patterns#1]
Thanks for all your work in this project.

For an app which normally loads using a storyboard, is it possible to use your patterns here to test ONLY one view controller at a time? i.e. the app starts completely black and then the test suite presents the target view controller onto the screen?

Currently the test suite loads the main storyboard and then other stuff is pushed on top, which is not the level of isolation I want.

**Comment by ccabanero** [comment]
Hey @fulldecent, in general, the approach presented here in most of the samples with ViewControllers - is that there is one TestCase class for each ViewController class.  

To test a View Controller, I do the following:

Step 1. Use @testable.  For example:
https://gist.github.com/ccabanero/b92197516342c0147688#file-unit-testing-samle-uibutton-swift-L3

Step 2: Create a property for your target view controller.  For example:
https://gist.github.com/ccabanero/b92197516342c0147688#file-unit-testing-samle-uibutton-swift-L7

Step 3: Fetch your view controller from a storyboard:
https://gist.github.com/ccabanero/b92197516342c0147688#file-unit-testing-samle-uibutton-swift-L7

**Comment by fulldecent** [comment]
This is excellent. I see you have

```
self.viewControllerUnderTest.loadView()
self.viewControllerUnderTest.viewDidLoad()
```

You are not actually presenting the VC and are not using make key and visible. Are there any special considerations needed when doing it this way?
